import { CurrentUser } from "../../types/current-user";

export type { CurrentUser };

export interface LoginRequest {
    email: string;
    password: string;
}

export interface LoginResponse {
    accessToken: string;
    refreshToken: string;
    expiresAt?: number;
    user: CurrentUser;
}

export interface ForgotPasswordRequest {
    email: string;
}

export interface ResetPasswordRequest {
    password: string;
}

/**
 * Data supplied by the Admin frontend
 * when creating a new employee.
 *
 * employeeId and roleId are deliberately
 * NOT supplied by the frontend.
 */
export interface RegisterRequest {
    email: string;
    password: string;
    name: string;
    surname: string;
    phone: string;
    address: string;
    jobTitle: string;
    roleId?: number;
}

/**
 * Response returned after successful
 * employee registration.
 *
 * employeeId is generated by the backend.
 */
export interface RegisterResponse {
    id: string;
    email: string;
    name: string;
    surname: string;
    employeeId: string;
}